backend:
  name: github
  repo: vittolom/Restaurant
  branch: main

media_folder: "images/menu"
public_folder: "/images/menu"

collections:
  - name: "piatti"
    label: "Menu"
    folder: "menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Prezzo", name: "prezzo", widget: "string" }
      - { label: "Descrizione", name: "descrizione", widget: "text" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Immagine", name: "immagine", widget: "image" }
